apiVersion: 1

datasources:
  - name: Prometheus
    uid: webstore-metrics
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
  - name: Jaeger
    uid: webstore-traces
    type: jaeger
    url: http://jaeger:16686/jaeger/ui
    editable: true
    isDefault: false
